# Site settings
title: Recipe Book
email:
description: "My recipe collection." # Be descriptive
keywords:
  - jekyll

# URL
# url:
baseurl: /recipe-book

# plugins
#plugins:
#  - "jekyll-github-metadata" # Helps resolves issues with baseurl and github pages. Use baseurl in links and this will resolve the correct base

#social
logo: assets/images/recipe-book-rev.svg
image: assets/images/recipe-book-logo.png
social-twitter:
social-facebook:
social-linkedin:
social-github:


#contacts
contact-email: ''
contact-address: ''
contact-phone: ''

#Timezone
timezone: Australia/Sydney

#Colors
## Need to be added to SCSS file - color-palettes
colors:
  - primary: 243,170,57,1
  - secondary: 21,56,108,1
  - accent: 217,47,79,1
  - warning: FFDC0B;
  - success: 318700;

# Fonts
## Need to be specifid in SCSS file - type-settings
fonts: https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700

# Maps
google_maps_javascript_api_key: ''
location:
  - lat: ''
    long: ''
    zoom: ''
    title: ''
    description: ''
    address:

# Contact Form API from 99inbound
99inbound:

# sass:
#  style: compressed

# encoding
encoding: utf-8

# Build settings
# markdown: kramdown

# Setup for pages
include: ["_pages"]
permalink: /:year/:title.html

# Setup for Categories
collections:
  recipes:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipes
